// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw43rm7zBfb2sojZSF6481PdMJFZhddTA',
    appId: '1:133046827119:web:7b2c1513e21ed9bbbb759a',
    messagingSenderId: '133046827119',
    projectId: 'clinio-6f2e2',
    authDomain: 'clinio-6f2e2.firebaseapp.com',
    storageBucket: 'clinio-6f2e2.firebasestorage.app',
    measurementId: 'G-DQZT1K0ZZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4KtqodjLdznS31F4OZEKDqx2_EWsjA2s',
    appId: '1:133046827119:android:0b39b91099504cfcbb759a',
    messagingSenderId: '133046827119',
    projectId: 'clinio-6f2e2',
    storageBucket: 'clinio-6f2e2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCisZYZYrhZyuKvN_YyAQw03FCi9qO6QyA',
    appId: '1:133046827119:ios:0f07e128e5cffcebbb759a',
    messagingSenderId: '133046827119',
    projectId: 'clinio-6f2e2',
    storageBucket: 'clinio-6f2e2.firebasestorage.app',
    iosBundleId: 'com.koba.clinio',
  );
}
